@extends('front.app')

@section('content')
    <style>
        .cookies-wrapper {
            background: linear-gradient(135deg, #f8fafc 0%, #edf2f7 100%);
            min-height: 100vh;
            padding: 4rem 1rem;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        }
        .cookies-container {
            max-width: 900px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05);
            overflow: hidden;
            border: 1px solid #e2e8f0;
        }
        .cookies-header {
            background: #0f172a;
            color: #ffffff;
            padding: 3rem 2.5rem;
            position: relative;
        }
        .cookies-header h1 {
            font-size: 2.25rem;
            font-weight: 800;
            letter-spacing: -0.025em;
            margin: 0 0 0.5rem 0;
            line-height: 1.2;
        }
        .cookies-header p {
            color: #94a3b8;
            font-size: 0.95rem;
            margin: 0;
        }
        .cookies-body {
            padding: 2.5rem;
        }
        .cookies-section {
            margin-bottom: 2.5rem;
        }
        .cookies-section h3 {
            font-size: 1.35rem;
            font-weight: 700;
            color: #1e293b;
            margin-top: 0;
            margin-bottom: 1.25rem;
            line-height: 1.4;
            display: flex;
            align-items: center;
        }
        .cookies-section h3::before {
            content: "";
            display: inline-block;
            width: 6px;
            height: 20px;
            background: #3b82f6;
            margin-right: 10px;
            border-radius: 3px;
        }
        .cookies-text {
            color: #475569;
            line-height: 1.7;
            font-size: 1.05rem;
            margin-bottom: 1.25rem;
        }
        @media (max-width: 768px) {
            .cookies-wrapper {
                padding: 1.5rem 0.5rem;
            }
            .cookies-header {
                padding: 2rem 1.5rem;
            }
            .cookies-header h1 {
                font-size: 1.75rem;
            }
            .cookies-body {
                padding: 1.5rem;
            }
        }
    </style>

    <div class="cookies-wrapper" data-aos="fade-up">
        <div class="cookies-container">

            <!-- Header matching the high-end UI design system -->
            <div class="cookies-header">
                <h1>Cookies Policy</h1>
                <p>Online Ireland Safety Course</p>
            </div>

            <div class="cookies-body">
                <div class="cookies-section" style="margin-bottom: 0;">

                    <h3>Ireland Safety Course Online - utilizes cookies for statistical data collection purposes.</h3>

                    <p class="cookies-text">
                        These cookies do not spread viruses nor can they access your hard drive. The website employs Google Analytics, a service provided by Google, Inc. (Google). Google Analytics uses cookies, which are text files placed on your computer, to analyze user interaction with the site. The information generated by these cookies, including your IP address, is transmitted to and stored on Google's servers in the United States.
                    </p>

                    <p class="cookies-text">
                        Google utilizes this data to assess website usage, compile reports on website activity for operators, and offer additional services related to internet usage and website activity. Google may share this information with third parties when required by law or when these parties process data on Google's behalf. Your IP address will not be associated with any other data held by Google.
                    </p>

                    <p class="cookies-text" style="margin-bottom: 0;">
                        Google utilizes this data to assess website usage, compile reports on website activity for operators, and offer additional services related to internet usage and website activity. Google may share this information with third parties when required by law or when these parties process data on Google's behalf. Your IP address will not be associated with any other data held by Google.
                    </p>

                </div>
            </div>

        </div>
    </div>
@endsection
